# Header
navname: Curriculum Vitae

# navigatior items
nav:
  # Archives: http://articles.meng.uno
  # Categories: http://categories.meng.uno
  # Tags: http://tags.meng.uno
  # Comments: http://comments.meng.uno
  Curriculum Vitae: /CV_Mengmeng_HKU.pdf

# favicon
favicon: /logo.png

# Profile
nickname: Mengmeng Kuang

### this variable is MarkDown form.
description: My name is Mengmeng Kuang, an Application Reseacher in Search Algorithm direction in <a href="https://www.tencent.com/en-us">Tencent</a> (<a href="https://www.wechat.com/en/">WeChat Group</a>) currently. Before that, I received an M.Phil degree in Computer Science from <a href="https://www.hku.hk">The University of Hong Kong</a>. I am fortunate to be supervised by Dr. <a href="https://www.cs.hku.hk/people/academic-staff/hfting">Hing-fung Ting</a>, who taught me how to do research. Prior to HKU, I received a B.Eng Degree in Computer Science from <a href="http://www.hit.edu.cn">Harbin Institute of Technology</a>, Harbin China, supervised by Prof. <a href="http://homepage.hit.edu.cn/zhaotiejun">Tiejun Zhao</a>. During that period, I learned a lot of basic knowledge about computer science and cultivated my interest in computer science research.
avatar: /image/avatar.png

# main menu navigation
## links key words should not be changed.
## Complete url after key words.
## Unused key can be commented out.
links:
  #Blog: http://home.meng.uno
  # Category:
  # Tags:
  # Link:
  # Resume:
  # Publish:
  # Trophy:
  # Gallery:
  # RSS:
  # AliPay:
  ZhiHu: https://www.zhihu.com/people/kuangmeng
  LinkedIn: https://www.linkedin.com/in/kuangmeng/
  # FaceBook:
  # Twitter:
  # Skype:
  # CodeSandBox:
  # CodePen:
  # Sketch:
  # Gitlab:
  # Dribbble:
  Instagram: https://instagram.com/kuangmengmeng
  # Reddit:
  # YouTube:
  # QQ:
  # Weibo:
  # WeChat:
  Github: https://github.com/kuangmeng

# how links show: you have 2 choice--text or icon.
links_text_enable: false
links_icon_enable: true

# Post page
## Post_meta
post_meta_enable: true

post_author_enable: true
post_date_enable: true
post_category_enable: true
## Post copyright
post_copyright_enable: true

post_copyright_author_enable: true
post_copyright_permalink_enable: true
post_copyright_license_enable: false
post_copyright_license_text: Copyright (c) 2019 <a href="http://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a> LICENSE
post_copyright_slogan_enable: false
post_copyright_slogan_text: Do you believe in <strong>DESTINY</strong>?
## toc
post_toc_enable: false

# Page
page_title_enable: false

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM D, YYYY
time_format: H:mm:ss

# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css

# scripts loaded in the end of the body
scripts:
  - /js/script.js
  - /js/tocbot.min.js
    # tscanlin/tocbot: Build a table of contents from headings in an HTML document.
    # https://github.com/tscanlin/tocbot


# plugin functions
## Mathjax: Math Formula Support
## https://www.mathjax.org
mathjax:
  enable: true
  import: demand # global or demand
  ## global: all pages will load mathjax,this will degrade performance and some grammers may be parsed wrong.
  ## demand: Recommend option,if your post need fomula, you can declare 'mathjax: true' in Front-matter
